apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service-deployment
  labels:
    app: users-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
      - name: users-service
        image: franrobles8/users-service:0.0.1
        ports:
        - containerPort: 8081
        env:
        - name: SERVICE_MONOLITH_URL
          value: "http://service-monolith:8080"
        - name: DB_URL
          value: "jdbc:mysql://db:3306/users"
        - name: DB_USER
          value: "root"
        - name: DB_PASS
          value: "pass"
---
kind: Service
apiVersion: v1
metadata:
  name: service-users-service
  labels:
    app: users-service
spec:
  ports:
    - name: http-users-service
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: users-service
  type: ClusterIP